# Generated by Django 6.0.1 on 2026-03-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_skill_level_userprofile_instrument_name'),
        ('accounts', '0005_userprofile_skill_level_userprofile_instrument_name'),
    ]

    operations = [
    ]
