# Generated by Django 6.0.1 on 2026-03-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profilecompletion'),
        ('accounts', '0006_merge_20260313_2307'),
    ]

    operations = [
    ]
