# Generated by Django 6.0.1 on 2026-03-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0005_profilecompletion_0006_merge_20260313_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether user has active premium subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_end_date',
            field=models.DateTimeField(blank=True, help_text='When premium access ends', null=True),
        ),
    ]
