# Generated by Django 6.0.1 on 2026-03-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_utils', '0004_aiquizquestion_audio_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedquiz',
            name='practice_step_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
