# Generated by Django 6.0.1 on 2026-03-13 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_utils', '0005_aigeneratedquiz_practice_step_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_step_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('song_title', models.CharField(max_length=255)),
                ('arrangement_title', models.CharField(max_length=255)),
                ('instrument', models.CharField(default='guitar', max_length=100)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('bpm', models.PositiveIntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('is_ai_composed', models.BooleanField(default=True)),
                ('status', models.CharField(default='Not Started', max_length=20)),
                ('best_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_completion_time', models.FloatField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat', models.FloatField()),
                ('event_type', models.CharField(choices=[('note', 'Note'), ('chord', 'Chord')], max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='ai_utils.aigeneratedsong')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
