# Generated by Django 6.0.1 on 2026-03-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_utils', '0002_aitoken_tokens_limit'),
        ('ai_utils', '0006_aigeneratedsong_aitimelineevent'),
    ]

    operations = [
    ]
