# Generated by Django 6.0.1 on 2026-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_dailyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='instrument',
            field=models.CharField(blank=True, default='Guitar', max_length=100),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='plan_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='recommended_lesson_slugs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='skill_level',
            field=models.CharField(blank=True, default='Beginner', max_length=50),
        ),
    ]
